import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ER in TS</h1>

        <div className={styles.grid}>
          <Link href="/mySubjModules">
            <a className={styles.card}>
              <h2>My Subjects and Modules</h2>
              <p>All Subjects and Modules we need</p>
            </a>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href="/mygroups">
            <a className={styles.card}>
              <h2>My Groups</h2>
              <p>All the groups we need</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
