import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { GroupsView } from "../store/features/groups/GroupsView";
import styles from "../styles/Home.module.css";

const MyGroups: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Groups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a data-cy="nav-home">Home</a>
        </Link>
        <h1 className={styles.title}>My Groups</h1>
        <GroupsView />
      </main>
    </div>
  );
};

export default MyGroups;
