import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { GroupsView } from "../store/features/groups/GroupsView";
import styles from "../styles/Home.module.css";

const MyGroups: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Groups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">Home</Link>
        <h1 className={styles.title}>My Groups</h1>
        <GroupsView />
      </main>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps = async ({ req }) => {
//   const SSR = withSSRContext({ req });

//   const response = (await SSR.API.graphql({
//     query: listTodos,
//     authMode: GRAPHQL_AUTH_MODE.API_KEY,
//   })) as {
//     auth;
//     data: ListTodosQuery;
//   };

//   return {
//     props: {
//       todos: response.data.listTodos.items,
//     },
//   };
// };

export default MyGroups;
