import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SubjectsModulesView } from "../store/features/subjects/SubjModulesView";
import styles from "../styles/Home.module.css";

const MySubjModules: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Subjects + Modules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">Home</Link>
        <h1 className={styles.title}>My Subjects and Modules</h1>
        <SubjectsModulesView />
      </main>
    </div>
  );
};

export default MySubjModules;
